language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tavorb
  password:
    secure: X12TymCB+Dd8ET6+B2b42+2MAGjQzpI1r9FTSI/9rmW/6qlhLsfSEP4nz7LHVDXLjufIqcYF6UHbrLrhIvs15SqDTv8DzTe5mSB8e224IIvEQ2szw57ssaQ7SfgZSl2Sykq6kMejz4CQGcsz+xtcQNJIN0jQFiz0qj79Xyo97jkdpMxqaOsw4FvC0LsxzhvsfZs3sJfRo7Gw/8XxNRiJgchzR18EkGuaOph4adCu34iwK50ftHiwUKHJ7Z69Y1HJdJdyQE8toOuWe201EoHZt75A6xAKppj8qrvtUcp0SfQrEMbOh4vIv1bpKq6qI6kvbzqH15/4tXSbqK7SuHHgqqlv55aJoNY6tNg3rKsmZhrJklpGSWmLwRJY3ZqISZhxyjRLwegeWA+5uxe6QdNtmr6aaI3KtfEnP0Qx+AEJP0LGQ+ilpeODdJLByPhVpyR0PFG6XdK6zcpWRY9Fe+XxT4XVVdJgYPoZlhmrCptlGwHSpbWjT2w8n+3ZnMzE/EjK0KFHZZaKqs7iIfcvyTVQqOGIFnU9O2K5EcKYsa2nZGVS5ye79JcZi1ej0Fkie03Ooph6eCjxRfE3CRHmevp6b7KaXkSx2NZ2qwHBGAYEx3rqpTtyNtBM1jiYb1Sy0ZLX33ueSV6tq0ljnwN0yU+6WyVeHPELCwATFVrGXP5TAT8=
  on:
    tags: true
    repo: tavorb/oasis_stat
    python: 3.8
